### ISSUE TITLE
Check broker compatibility

### ISSUE THREAD

**Issue by spiegela** [codedellemc/ecs-cf-service-broker#14]
Compatibility is confirmed against service broker API 2.8.  Need to determine and document Cloud Foundry release compatibility with that, and check previous service broker API releases.

**Comment by spiegela** [comment]
I believe this is covered in the concourse-ci testing that has been added.  I will check with CF Persi team.

**Comment by paulcwarren** [comment]
Our CI will inherently check that the broker runs against the latest CF with whatever version of the service broker API it supports.

**Comment by spiegela** [comment]
Awesome.  I've also updated the README to reflect the Concourse testing.
